# Используем официальный Python 3.12 slim образ
FROM python:3.12-slim

WORKDIR /code

COPY requirements.txt /code

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . /code/

EXPOSE 5555

CMD ["uvicorn", "src.api.run_fastapi:app", "--host", "0.0.0.0", "--port", "5555", "--reload"]
